---
abstract: 'RTx-AddServiceData Extension'
author:
  - 'Marius Hein <marius.hein@netways.de'
build_requires:
  ExtUtils::MakeMaker: '6.59'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.68, CPAN::Meta::Converter version 2.150005'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: RTx-AddServiceData
no_index:
  directory:
    - t
    - inc
requires:
  perl: '5.010'
version: v0.9.0
x_serialization_backend: 'CPAN::Meta::YAML version 0.016'
